#!/usr/bin/env bash
# Install nginx web server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c "echo 'Holberton School' > /usr/share/nginx/html/index.html"
sudo service nginx restart