#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c "echo 'Holberton School' > /var/www/html/index.html"
sudo service nginx restart
