#!/usr/bin/env bash
# redirect page

./3-redirection
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
