#!/usr/bin/env bash
# redirect page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
sudo service nginx restart
