#!/usr/bin/env bash
# Add header to Nginx config file

HEADER='X-Served-By'
HOST_NAME=$(hostname)
sudo sed -i "s/http {/http {\n\tadd_header \$HEADER \$HOST_NAME;/" /etc/nginx/nginx.conf
sudo service nginx restart
