#!/usr/bin/env bash
# Add header to Nginx config file

HEADER='X-Served-By'
HOSTNAME=$(hostname)
sudo sed -i "s/http {/http {\n\tadd_header $HEADER $HOSTNAME;/" /etc/nginx/nginx.conf
sudo service nginx restart
