#!/usr/bin/env bash
# Add header to Nginx config file

sudo apt-get -y update
sudo apt-get -y install nginx
HOSTNAME=$(hostname)
sudo sed -i "s/http {/http {\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf
sudo service nginx restart
