#!/usr/bin/env bash
# Install load balancer

apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 1035-webs
    bind 0.0.0.0:80
    balance roundrobin
    server 1035-web-01 34.75.185.85:80 check
    server 1035-web-02 34.73.88.228:80 check
" >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy
