#!/usr/bin/env bash
# Install load balancer

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy=1.8.\*
printf %s "listen 1035-webs
    bind :80
    balance roundrobin
    server 1035-web-01 34.75.185.85:80 check
    server 1035-web-02 34.73.88.228:80 check
" >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy
