#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

for ((i=1;i<=100;i++))
do
    if ! ((i%15))
    then
        echo "FizzBuzz"
    elif ! ((i%3))
    then
        echo "Fizz"
    elif ! ((i%5))
    then
        echo "Buzz"
    else
        echo $i
    fi
done
